#!/usr/bin/env bash                                               
# Configure new server --> engine-x                               
                                                                
 apt-get -y update                                            
 apt-get -y install nginx                                     
 ufw allow 'Nginx HTTP'                                       
 sed -i 's/http {/&\n\tadd_header X-Served-By $HOSTNAME;/' /etc/nginx/nginx.conf
 service nginx restart
