#!/usr/bin/env bash
# displays numbers from 1 to 100
count=0
while [ $count -lt 100 ]; do
	(( count+=1 ))
	if (( count % 3 == 0 )) && (( count % 5 == 0 )); then
		echo "FizzBuzz"
	continue
	elif (( count % 3 == 0 )); then
		echo "Fizz"
	continue
	elif ((  count % 5 == 0 )); then
		echo "Buzz"
	continue
	fi
	echo "$count"
done
