#!/usr/bin/env bash
# This script is displaying 20 numbers with badluck on specific countries

count=0

while [ $count -lt 20 ]
do
  ((count++))
case $count in

  4)
    echo '4'
    echo "bad luck from China"
    ;;

  9)
    echo '9'
    echo "bad luck from japan"
    ;;

  14)
    echo '14'
    echo "bad luck from Italy"
    ;;

  *)
    echo "$count"
    ;;
esac
done
